# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rets}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["scrosley"]
  s.date = %q{2010-11-22}
  s.description = %q{This borrows heavily from the rets4r gem. I've only included certain features that I know to work. 
                         For example it has only been tested on RETS 1.7 and Ruby 1.9.2.
                         At some point the minor changes that were made can hopefully just be added to rets4r.
                      }
  s.email = %q{secrosley@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "examples/client_login.rb",
     "examples/client_search.rb",
     "lib/rets.rb",
     "lib/rets/auth.rb",
     "lib/rets/client.rb",
     "lib/rets/core-ext/hash/keys.rb",
     "lib/rets/dataobject.rb",
     "lib/rets/parsers/compact.rb",
     "lib/rets/parsers/response_parser.rb",
     "lib/rets/transaction.rb",
     "rets.gemspec",
     "test/rets_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/Shazzaam/rets}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{API for connection to RETS Server}
  s.test_files = [
    "test/rets_test.rb",
     "test/test_helper.rb",
     "examples/client_login.rb",
     "examples/client_search.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end
